### ISSUE TITLE
Join form email field looks like a button

### ISSUE THREAD

**Issue by jerath** [elsieC/shiny-ironman#127]
It looks like a button because the text is centered. "Your email here"?

This form looks really good though and this is not a priority. 

**ALSO** when tackling this issue, take btn-pad-top class out of the button if it's there

![screen shot 2015-07-21 at 10 31 02 am](https://cloud.githubusercontent.com/assets/5976978/8807812/b71bb62c-2f93-11e5-9823-6d93796ef6fb.png)

**Comment by elschan** [comment]
chnged plachole
