### ISSUE TITLE
Replying to comment as a non-member

### ISSUE THREAD

**Issue by jerath** [elsieC/shiny-ironman#81]
Ah I see. It still gives me the option to reply to a comment if I'm not logged in.

Restrict access to this by checking if member_signed_in? before displaying the default comment and reply link.

![screen shot 2015-07-19 at 9 54 14 am](https://cloud.githubusercontent.com/assets/5976978/8766824/3c4183de-2dfc-11e5-9071-374700ff0efb.png)

**Comment by elschan** [comment]
fixed
